AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  margins.me-annotation-utils

  Sample SAM Template for margins.me-annotation-utils

# Globals:
# Function:
#   Environment:
#     Variables:
#       STAGE: Production
#       TABLE_NAME: global-table

# Resources:
# MyFunction:
#   Type: AWS::Serverless::Function
#   Properties:
#     Environment:
#       Variables:
#         TABLE_NAME: resource-table
#         NEW_VAR: hello
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
# Globals:
#   Function:
#     Timeout: 30

Parameters:
  CognitoUserPoolId:
    Type: String
  CognitoUserPoolArn:
    Type: String
  AWSAccountId:
    Type: String
  GraphqlEndpoint:
    Type: String
  PrivateKey:
    Type: String

Resources:
  SESLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/reject-unregistered-emails
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      FunctionName: SESRejectUnregisteredEmails
      Policies:
        - AmazonCognitoReadOnly
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
      Timeout: 30
  CognitoPostConfirmLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/cognito-post-confirm
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      FunctionName: CognitoPostConfirmLambda
      Environment:
        Variables:
          GRAPHQL_ENDPOINT: !Ref GraphqlEndpoint
          PRIVATE_KEY: !Ref PrivateKey
      Policies:
        - Version: 2012-10-17
          Statement:
            Sid: AllowCognitoAdminActions
            Effect: Allow
            Action:
              - cognito-idp:Admin*
            Resource: !Ref CognitoUserPoolArn
      Timeout: 30
  S3ParseKindleEmailLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/parse-kindle-email
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      FunctionName: S3ParseKindleEmailLambda
      Timeout: 30
      Policies:
        Version: '2012-10-17'
        Statement:
          - Sid: ListObjectsInBucket
            Effect: Allow
            Action:
            - s3:ListBucket
            Resource:
            - arn:aws:s3:::margins.me-uploads
          - Sid: AllObjectActions
            Effect: Allow
            Action: s3:*Object
            Resource:
            - arn:aws:s3:::margins.me-uploads/*

## ALLOW COGNITO TO INVOKE
#   - Version: '2012-10-17'
#     Statement:
#       Sid: AllowCognitoPostConfirmationTrigger
#       Effect: Allow
#       Principal:
#         Service: cognito-idp.amazonaws.com
#       Action: lambda:InvokeFunction
#       Resource: !Sub "arn:aws:lambda:us-east-1:${AWSAccountId}:function:CognitoPostConfirmLambda"
#       Condition:
#         ArnLike:
#           AWS:SourceArn: !Ref CognitoUserPoolArn

## ALLOW SES TO INVOKE
# {
# "Version": "2012-10-17",
# "Id": "default",
# "Statement": [
#   {
#     "Sid": "allowSesInvoke",
#     "Effect": "Allow",
#     "Principal": {
#       "Service": "ses.amazonaws.com"
#     },
#     "Action": "lambda:InvokeFunction",
#     "Resource": "arn:aws:lambda:us-east-1:516851544810:function:sam-test-SESLambda-D7BP58TEQ5KN",
#     "Condition": {
#       "StringEquals": {
#         "AWS:SourceAccount": "516851544810"
#       }
#     }
#   }
# }

# Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  # HelloWorldFunction:
  #   Description: "Hello World Lambda Function ARN"
  #   Value: !GetAtt HelloWorldFunction.Arn
  # HelloWorldFunctionIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
