AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  margins.me-annotation-utils

  Sample SAM Template for margins.me-annotation-utils

# Globals:
# Function:
#   Environment:
#     Variables:
#       STAGE: Production
#       TABLE_NAME: global-table

# Resources:
# MyFunction:
#   Type: AWS::Serverless::Function
#   Properties:
#     Environment:
#       Variables:
#         TABLE_NAME: resource-table
#         NEW_VAR: hello
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 100

Resources:
  SESLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: email-utils/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - AmazonCognitoReadOnly
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: us-east-1_jcGG3tVBb

# Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  # HelloWorldFunction:
  #   Description: "Hello World Lambda Function ARN"
  #   Value: !GetAtt HelloWorldFunction.Arn
  # HelloWorldFunctionIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
