service: margins-me-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  endpointType: REGIONAL
  deploymentBucket:
    name: serverless-margins-me
    serverSideEncryption: AES256


resources:
  Resources:
    HttpApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: MarginsMe-HttpApiGateway
        Description: Lambda Proxy
        ProtocolType: HTTP
    HttpApiId:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /margins.me/dev/api-gateway/id
        Type: String
        Value:
          Ref: HttpApi

  # Outputs:
  #   httpApiId:
  #     Value:
  #       Ref: HttpApi
  #     Export:
  #       Name: MarginsMe-HttpApiGateway