service: margins-me-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  endpointType: REGIONAL
  deploymentBucket:
    name: serverless-margins-me
    serverSideEncryption: AES256

resources:
  Resources:
    MarginsMe-HttpApiGateway:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: MarginsMe-HttpApiGateway
        Description: Lambda Proxy
        ProtocolType: HTTP

  Outputs:
    httpApiId:
      Value:
        Ref: MarginsMe-HttpApiGateway
      Export:
        Name: MarginsMe-HttpApiGateway