service: margins-me-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  endpointType: REGIONAL
  deploymentBucket:
    name: serverless-margins-me
    serverSideEncryption: AES256

custom:
  domains:
    prod: api.margins.me
    staging: staging-api.margins.me
    dev: dev-api.margins.me
  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: '*.margins.me'
    apiType: http
    endpoinType: regional

resources:
  Resources:
    MarginsMeHttpApiGateway:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: MarginsMe-HttpApiGateway
        Description: Lambda Proxy
        ProtocolType: HTTP

  Outputs:
    httpApiId:
      Value:
        Ref: MarginsMeHttpApiGateway
      Export:
        Name: MarginsMe-HttpApiGateway