version: "3.3"
services:
  db:
    container_name: margins-testing-db
    restart: always
    image: margins-testing-db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 8000:5432
    command: ["postgres", "-c", "log_statement=all"]


  graphql:
    container_name: margins-testing-graphql
    restart: always
    image: margins-testing-graphql
    build:
      context: ./graphql
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - 8001:8080


volumes:
  db: