version: "3.3"
services:
  db:
    container_name: margins-testing-db
    restart: always
    image: margins-testing-db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 5432:5432

  graphql:
    container_name: margins-testing-graphql
    restart: always
    image: margins-testing-graphql
    build:
      context: ./graphql
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - network
    ports:
      - 5433:5433
    command: ["--connection", "${DATABASE_URL}", "--port", "5433", "--schema", "margins_private", "append-plugins", "postgraphile-plugin-connection-filter", "@graphile-contrib/pg-many-to-many"]

networks:
  network:

volumes:
  db: