service: ${env:AWS_SERVICE_NAME}

app: margins-me
org: alexliusq


plugins:
  - serverless-content-encoding
  - serverless-sam
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-domain-manager

custom:
  contentEncoding:
    minimumCompressionSize: 0
  # bundle:
  #   ignorePackages:
  #     - pg-native
  #   linting: true
  #   packager: yarn
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
    keepOutputDirectory: true
  domains:
    prod: api.margins.me
    staging: staging-api.margins.me
    dev: dev-api.margins.me
  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: '*.margins.me'
    apiType: http
    endpointType: regional

package:
  individually: true
  # include: src/postgraphile.cache

provider:
  name: aws
  runtime: nodejs12.x
  deploymentBucket:
    name: ${env:AWS_SERVICE_NAME}
  region: ${env:AWS_REGION_CUSTOM}
  stage: ${env:AWS_STAGE}

functions:
  graphql:
    handler: src/index.handler # Actual handler substituted in during deploy script
    events:
      - http:
          method: post
          path: graphql
          cors: true
          integration: lambda-proxy
    environment:
      DATABASE_URL: ${env:DATABASE_URL}
      DATABASE_SCHEMAS: ${env:DATABASE_SCHEMAS}
      JWT_SECRET: ${env:JWT_SECRET}
      JWT_PG_TYPE_IDENTIFIER: ${env:JWT_PG_TYPE_IDENTIFIER}
    vpc:
      securityGroupIds:
        "Fn::Split":
          - ","
          - ${env:AWS_VPC_SECURITY_GROUP_IDS}
      subnetIds:
        "Fn::Split":
          - ","
          - ${env:AWS_VPC_SUBNET_IDS}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "ec2:CreateNetworkInterface"
          - "ec2:DescribeNetworkInterfaces"
          - "ec2:DetachNetworkInterface"
          - "ec2:DeleteNetworkInterface"
        Resource: "*"
