version: "3.3"
services:
  db:
    container_name: margins-testing-db
    restart: always
    image: margins-testing-db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]


  graphql:
    container_name: margins-testing-graphql
    restart: always
    image: margins-testing-graphql
    build:
      context: ./graphql
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - 8080:8080
  
  webserver:
    container_name: webserver
    restart: unless-stopped
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - web-root:/var/www/html
      # - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - graphql
    
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email alexliusiqing@gmail.com --agree-tos --no-eff-email -d api.margins.me


volumes:
  db:
  certbot-etc:
  certbot-var:
  web-root: